server:
  port: 8081

spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:mysql://localhost:3306/lms_auth
    username: root
    password: kishore
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  config:
    import: optional:configserver:http://localhost:8088

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

jwt:
  secret: vJ9s3XqK8eZrQ1uYxG5pT2fL9cW8dA3mN7oBvE6hJ4sKqT9uXyZcV1rL8gH2eM5nQ

