server:
  port: 8080

spring:
  application:
    name: api-gateway
  config:
    import: configserver:http://localhost:8888
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**
        - id: course-service
          uri: lb://course-service
          predicates:
            - Path=/api/courses/**
        - id: enrollment-service
          uri: lb://enrollment-service
          predicates:
            - Path=/api/enrollments/**
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**
    discovery:
      locator:
        enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
