server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/lms_users
    username: root
    password: kishore

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  cloud:
    config:
      enabled: false

  config:
    import-check:
      enabled: false
