spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/lms_users
    username: root
    password: kishore
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  config:
    import: configserver:http://localhost:8888
  cloud:
    config:
      enabled: true

server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

feign:
  client:
    config:
      default:
        connectTimeout: 3000
        readTimeout: 3000
        loggerLevel: full

auth:
  service:
    url: http://localhost:8081/

jwt:
  secret: ksndfksnksjdfjnsgijsdijsdnuhdiajsidndugeijwdgu73.,y!
  expiration: 3600