server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Sai-kishore-veeranki/lms-backend
          username: Sai-kishore-veeranki
          password: Saikishoreveeranki@1
          default-label: main
          clone-on-start: true
          skip-ssl-validation: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
